"use client";
import { useCallback, useEffect, useState } from "react";
import { DashboardHeader } from "@/components/dashboard-header";
import { ApiKeyItem } from "@/components/api-key-item";
import { CreateApiKeyDialog } from "@/components/create-api-key-dialog";
import axios from "axios";
import { useUserContext } from "@/app/context/contextProvider";

export interface ApiKey {
  id: string;
  name: string;
  key: string;
  createdAt: string;
}

export default function ApiKeyDashboard() {
  const userContext = useUserContext();
  const [countAPI, setCountAPI] = useState<number>(0);
  const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [loading, setLoading] = useState<boolean>(true);

  const handleCreateApiKey = async (name: string) => {
    try {
      setLoading(true);
      const userid = userContext?.user;
      const response = await axios.post(
        "/api/v1/dashboard/key/generate",
        {
          name,
          userid,
        },
        {
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
          },
        }
      );
      const { data } = response.data;

      // removing the apiKeys state
      setApiKeys([]);

      /*
      Array to store the values of the apis in the local storage
      */
      const localStorageKeys: string[] = [];

      // @ts-expect-error "Value type is not defined"
      data.map((value) => {
        setCountAPI(data.length);
        localStorageKeys.push(value.key);
        setApiKeys((prev) => {
          return [
            ...prev,
            {
              id: value._id,
              name: value.name,
              key: value.key,
              createdAt: value.createdAt,
            },
          ];
        });
      });
      localStorage.setItem("keys", JSON.stringify(localStorageKeys));
      return;
    } catch (error) {
      console.log("Error while creating a new api key:", error);
    } finally {
      setLoading(false);
      setIsCreateDialogOpen(false);
    }
  };

  // Deletes the api key and updates the local storage with the new api values
  const handleDeleteApiKey = async (id: string) => {
    setCountAPI((prev) => prev - 1);
    setApiKeys(apiKeys.filter((key) => key.id !== id));
    const updatedApiKeys = await axios.delete(
      `/api/v1/dashboard/key/remove?key=${id}`
    );
    const { data } = updatedApiKeys.data;

    // Array for API keys in local storage
    const localStorageKeys: string[] = [];

    // Removes all the keys from the local storage when keys/data is not present in the data object
    if (!data?.keys) {
      // Removes the key from local storage
      localStorage.removeItem("keys");
      return;
    }

    // TODO: add the types
    // @ts-expect-error "Types not defined"
    data.keys.map((value) => localStorageKeys.push(value.key));

    // Updating the localStorage with new api values
    localStorage.setItem("keys", JSON.stringify(localStorageKeys));
  };

  // Filters the api key based on the name
  const filteredKeys = apiKeys.filter((key) =>
    key.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Get all the api keys from the db the user has created and update the local storage with the api key values
  const getApiKeys = useCallback(async (userid: string | undefined) => {
    try {
      if (!userid) return;
      setLoading(true);

      /* Key value to be stored in the local storage for faster retrieval on other routes */

      // Removes the existing keys
      localStorage.removeItem("keys");
      // Array of keys for the local storage
      const localStorageKeys: string[] = [];

      const userApiKeysResponse = await axios.get(
        `/api/v1/dashboard/key?userid=${userid}`
      );
      const { data } = userApiKeysResponse.data;

      // Clears the existing API keys to prevent duplicates from being rendered on the screen
      setApiKeys([]);

      // Updates the count of API keys generated by the user based on the length of the data
      setCountAPI(data.length);
      // @ts-expect-error "Value type is not defined"
      data.map((value) => {
        /*
        Appending the API key value into the array of keys(for local storage only)
        */
        localStorageKeys.push(value.key);

        setApiKeys((prev) => {
          return [
            ...prev,
            {
              id: value._id,
              name: value.name,
              key: value.key,
              createdAt: value.createdAt,
            },
          ];
        });
      });

      /* Sets the local storage with api keys value */
      localStorage.setItem("keys", JSON.stringify(localStorageKeys));
    } catch (error) {
      console.log("Error in getApiKeys", error);
      setApiKeys([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const userid = userContext?.user;
    console.log("User id in useEffect", userid);

    getApiKeys(userid);

    // Cleanup function
    return () => {
      setLoading(true);
      setApiKeys([]);
      setCountAPI(0);
    };
  }, [getApiKeys, userContext]);

  return (
    <>
      <DashboardHeader
        onSearch={setSearchTerm}
        onCreateNew={() => setIsCreateDialogOpen(true)}
        countAPI={countAPI}
      >
        <div className="space-y-4">
          {filteredKeys &&
            !loading &&
            filteredKeys.map((apiKey) => (
              <ApiKeyItem
                key={apiKey.id}
                apiKey={apiKey}
                onDelete={() => handleDeleteApiKey(apiKey.id)}
              />
            ))}
          {filteredKeys.length === 0 && !loading && (
            <div className="text-center text-muted-foreground py-8">
              No API keys found. Create a new one to get started.
            </div>
          )}
        </div>
      </DashboardHeader>
      <CreateApiKeyDialog
        isOpen={isCreateDialogOpen}
        onClose={() => setIsCreateDialogOpen(false)}
        onCreate={handleCreateApiKey}
      />
    </>
  );
}
