"use client";
import { useCallback, useEffect, useState } from "react";
import { DashboardLayout } from "@/components/dashboard-layout";
import { ApiKeyItem } from "@/components/api-key-item";
import { CreateApiKeyDialog } from "@/components/create-api-key-dialog";
import axios from "axios";
import { useUserContext } from "@/app/context/contextProvider";
import { useRouter } from "next/navigation";

export interface ApiKey {
  id: string;
  name: string;
  key: string;
  createdAt: string;
}

export default function ApiKeyDashboard() {
  const userContext = useUserContext();
  const [countAPI, setCountAPI] = useState<number>(0);
  const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [loading, setLoading] = useState<boolean>(true);
  const router = useRouter();

  const handleCreateApiKey = async (name: string) => {
    try {
      setLoading(true);
      const userid = userContext?.user;
      const response = await axios.post(
        "/api/v1/dashboard/key/generate",
        {
          name,
          userid,
        },
        {
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
          },
        }
      );
      const { data } = response.data;

      // removing the apiKeys state
      setApiKeys([]);

      // @ts-expect-error "Value type is not defined"
      data.map((value) => {
        setCountAPI(data.length);
        setApiKeys((prev) => {
          return [
            ...prev,
            {
              id: value._id,
              name: value.name,
              key: value.key,
              createdAt: value.createdAt,
            },
          ];
        });
      });
      return;
    } catch (error) {
      console.log("Error while creating a new api key:", error);
    } finally {
      setLoading(false);
      setIsCreateDialogOpen(false);
    }
  };

  // Deletes the api key
  const handleDeleteApiKey = async (id: string) => {
    setCountAPI((prev) => prev - 1);
    setApiKeys(apiKeys.filter((key) => key.id !== id));
    await axios.delete(`/api/v1/dashboard/key/remove?key=${id}`);
  };

  // Filters the api key based on the name
  const filteredKeys = apiKeys.filter((key) =>
    key.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Get all the api keys from the db the user has created
  const getApiKeys = useCallback(async (userid: string | undefined) => {
    try {
      if (!userid) return;
      setLoading(true);
      const userApiKeysResponse = await axios.get(
        `/api/v1/dashboard/key?userid=${userid}`
      );
      const { data } = userApiKeysResponse.data;

      // Clears the existing API keys to prevent duplicates from being rendered on the screen
      setApiKeys([]);

      // Updates the count of API keys generated by the user based on the length of the data
      setCountAPI(data.length);
      // @ts-expect-error "Value type is not defined"
      data.map((value) => {
        setApiKeys((prev) => {
          return [
            ...prev,
            {
              id: value._id,
              name: value.name,
              key: value.key,
              createdAt: value.createdAt,
            },
          ];
        });
      });
    } catch (error) {
      console.log("Error in getApiKeys", error);
      setApiKeys([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const userid = userContext?.user;
    console.log("User id in useEffect", userid);

    getApiKeys(userid);

    // Cleanup function
    return () => {
      setLoading(true);
      setApiKeys([]);
      setCountAPI(0);
    };
  }, [getApiKeys, userContext]);

  return (
    <>
      <DashboardLayout
        onSearch={setSearchTerm}
        onCreateNew={() => setIsCreateDialogOpen(true)}
        countAPI={countAPI}
      >
        <div className="space-y-4">
          {filteredKeys &&
            !loading &&
            filteredKeys.map((apiKey) => (
              <ApiKeyItem
                key={apiKey.id}
                apiKey={apiKey}
                onDelete={() => handleDeleteApiKey(apiKey.id)}
              />
            ))}
          {filteredKeys.length === 0 && !loading && (
            <div className="text-center text-muted-foreground py-8">
              No API keys found. Create a new one to get started.
            </div>
          )}
        </div>
      </DashboardLayout>
      <CreateApiKeyDialog
        isOpen={isCreateDialogOpen}
        onClose={() => setIsCreateDialogOpen(false)}
        onCreate={handleCreateApiKey}
      />
    </>
  );
}
